# Generated by Django 4.2.5 on 2023-10-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisements',
        ),
    ]
